### ISSUE TITLE
Help for fuzzing screen

### ISSUE THREAD

**Issue by HangShuLYH** [RUB-SysSec/aurora#11]
Sorry to bother. When I'm doing the experiment of screen heap buffer overflow, the fourth test case in the paper, I don't know how to fuzz the program.
Would you please show me the cmd line to fuzz it？
Thanks for your help

**Comment by mu00d8** [comment]
hi,

the arguments for screen (as expected in `arguments.txt`) should be `-D -m cat @@`

**Comment by just4surfing** [comment]
@HangShuLYH Hi, have you succeeded in reproducing this bug? I have tried the `-D -m cat @@` flag as well as the crashing input provided in [the fix commit](https://git.savannah.gnu.org/cgit/screen.git/commit/?id=68386dfb1fa33471372a8cd2e74686758a2f527b), but non seems to crash `screen`. 

P.S. I experimented on screen commit `c5db181b6e017cfccb8d7842ce140e59294d9f62 ` ([as pointed out here](https://ubuntu.com/security/CVE-2020-9366)) and the parent commit of [the fix commit](https://git.savannah.gnu.org/cgit/screen.git/commit/?id=68386dfb1fa33471372a8cd2e74686758a2f527b)

**Comment by mu00d8** [comment]
Did you run configure with `--enable-rxvt_osc`?

**Comment by x0v0l** [comment]
@mu00d8 Hi. Sorry to bother. I'm confused with the fourth test case in the paper.
I can crash screen manually, but still have problem in fuzzing it . I can start screen first and then use command "echo -e ..." to crash it. That's two steps in total. However, I failed to crash screen by a single cmd line, which is needed in fuzzing.
I tried some combination, none of which succeeded. They are as follows: 
1. put the command "echo -e ..." in poc_file, and use command "./screen -D -m < poc_file"
2. put the command "echo -e ..." in poc_file, and use command "./screen -D -m cat poc_file"
3. I've also tried to replace the flag `-D -m` with different combinations of arguments, but didn't succeed.
Could you please tell me what should poc_file contain exactly, and what screen arguments (what command) should I use with the poc_file, in order to crash it by a single command, and to fuzz it finally.
Thanks so much for helping me with this issue! :)

**Comment by mu00d8** [comment]
Hi, sorry for the late response! To crash screen, the following steps should suffice:
```bash
# generate poc file
echo -e "\e]49\e;                                    \n\ec" > poc_file
# run screen 
./screen -D -m cat poc_file
```
Importantly, the `echo -e` is only used to generate the poc file, not in the actual command or poc file.

**Comment by tiedaoxiaotubie** [comment]
您的邮件我已经收到了，我会尽快处理然后给你回复。谢谢！
